// Generated by CoffeeScript 2.7.0
(function() {
  var notes;

  notes = ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'];

  this.getFrequency = function(noteN) {
    return 440 * 2 ** ((noteN - 49) / notes.length);
  };

  this.getNoteN = function(noteStr) {
    var i, octave;
    i = notes.indexOf(noteStr.slice(0, -1));
    octave = parseInt(noteStr.slice(-1));
    if (i >= notes.indexOf('C')) {
      octave -= 1;
    }
    return octave * notes.length + i + 1;
  };

}).call(this);
